mysql:
  image: mysql:5.7.14
  volumes:
    - ./mysql/:/var/lib/mysql/
  ports:
    - "127.0.0.1:8002:3306"
  environment:
    MYSQL_ROOT_PASSWORD: 123456
    MYSQL_USER: dev
    MYSQL_PASSWORD: 123456
    MYSQL_DATABASE: myapp
  log_opt:
    max-size: 15k

redis:
  image: redis:3.2.1-alpine
  restart: on-failure:5
  command: redis-server --notify-keyspace-events AEK
  ports:
    - "127.0.0.1:8001:6379"
  log_opt:
    max-size: 15k


webapp:
  extends:
    file: ./symfony/docker/docker-compose.yml
    service: webapp
  environment:
    VIRTUAL_HOST: 'https://app.symfony.local,app.symfony.local'
  links:
    - webapp_php
  log_opt:
    max-size: 15k
webapp_php:
  extends:
    file: ./symfony/docker/docker-compose.yml
    service: webapp_php
  links:
    - mysql
    - redis
  log_opt:
    max-size: 15k

proxy:
  image: dockercloud/haproxy:1.3
  ports:
    - "127.0.0.1:80:80"
    - "127.0.0.1:443:443"
 # volumes:
 #   - ./ssl/cert.pem:/certs/cert.pem
 # environment:
 #   CERT_FOLDER: /certs/
  links:
    - webapp
  log_opt:
    max-size: 20k

