webapp:
  image: nginx:alpine
  volumes:
    - ../:/app/
    - ./vhosts/:/etc/nginx/conf.d/
  restart: on-failure:5
webapp_php:
  build: ./php7
  working_dir: /app/
  environment:
    APP_ENV: development
  volumes:
    - ../:/app/
